spring:
  application:
    name: currency-service

server:
  port: 2222

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 10   #生产环境上，这个值得设为30
    initial-instance-info-replication-interval-seconds: 5  #生产环境上，这个值得设为10
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  #生产环境上，这个值得设为30
    lease-expiration-duration-in-seconds: 10   #生产环境上，这个值得设为30
  server:
    waitTimeInMsWhenSyncEmpty: 0
    registrySyncRetries: 0