--- # webserver
server:
  port: 1111

spring:
  application:
    name: eureka-server
    
eureka:
  client:
    registerWithEureka: false #默认情况服务注册中心也会将自己作为客户端来尝试注册它自己，false表示不注册，如果是eureka集群模式，请设为true
    fetchRegistry: false #从注册中心获取注册服务信息，如果是eureka集群模式，请设为true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true #实例名称显示IP
  server:
    enableSelfPreservation: false